# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('surname', models.CharField(db_index=True, max_length=80)),
                ('birth', models.DateField(help_text='DD.MM.YYYY')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
